// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: C2S.proto

#ifndef PROTOBUF_C2S_2eproto__INCLUDED
#define PROTOBUF_C2S_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "MsgId_pb.h"
// @@protoc_insertion_point(includes)

namespace tetris_protocol {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_C2S_2eproto();
void protobuf_AssignDesc_C2S_2eproto();
void protobuf_ShutdownFile_C2S_2eproto();

class C2SLogin;
class C2SMsg;

// ===================================================================

class C2SLogin : public ::google::protobuf::Message {
 public:
  C2SLogin();
  virtual ~C2SLogin();
  
  C2SLogin(const C2SLogin& from);
  
  inline C2SLogin& operator=(const C2SLogin& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const C2SLogin& default_instance();
  
  void Swap(C2SLogin* other);
  
  // implements Message ----------------------------------------------
  
  C2SLogin* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const C2SLogin& from);
  void MergeFrom(const C2SLogin& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 channelId = 1;
  inline bool has_channelid() const;
  inline void clear_channelid();
  static const int kChannelIdFieldNumber = 1;
  inline ::google::protobuf::int32 channelid() const;
  inline void set_channelid(::google::protobuf::int32 value);
  
  // required string channelAccountId = 2;
  inline bool has_channelaccountid() const;
  inline void clear_channelaccountid();
  static const int kChannelAccountIdFieldNumber = 2;
  inline const ::std::string& channelaccountid() const;
  inline void set_channelaccountid(const ::std::string& value);
  inline void set_channelaccountid(const char* value);
  inline void set_channelaccountid(const char* value, size_t size);
  inline ::std::string* mutable_channelaccountid();
  inline ::std::string* release_channelaccountid();
  
  // optional string loginToken = 3;
  inline bool has_logintoken() const;
  inline void clear_logintoken();
  static const int kLoginTokenFieldNumber = 3;
  inline const ::std::string& logintoken() const;
  inline void set_logintoken(const ::std::string& value);
  inline void set_logintoken(const char* value);
  inline void set_logintoken(const char* value, size_t size);
  inline ::std::string* mutable_logintoken();
  inline ::std::string* release_logintoken();
  
  // @@protoc_insertion_point(class_scope:tetris_protocol.C2SLogin)
 private:
  inline void set_has_channelid();
  inline void clear_has_channelid();
  inline void set_has_channelaccountid();
  inline void clear_has_channelaccountid();
  inline void set_has_logintoken();
  inline void clear_has_logintoken();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* channelaccountid_;
  ::std::string* logintoken_;
  ::google::protobuf::int32 channelid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_C2S_2eproto();
  friend void protobuf_AssignDesc_C2S_2eproto();
  friend void protobuf_ShutdownFile_C2S_2eproto();
  
  void InitAsDefaultInstance();
  static C2SLogin* default_instance_;
};
// -------------------------------------------------------------------

class C2SMsg : public ::google::protobuf::Message {
 public:
  C2SMsg();
  virtual ~C2SMsg();
  
  C2SMsg(const C2SMsg& from);
  
  inline C2SMsg& operator=(const C2SMsg& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const C2SMsg& default_instance();
  
  void Swap(C2SMsg* other);
  
  // implements Message ----------------------------------------------
  
  C2SMsg* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const C2SMsg& from);
  void MergeFrom(const C2SMsg& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required .tetris_protocol.MsgId msgId = 1;
  inline bool has_msgid() const;
  inline void clear_msgid();
  static const int kMsgIdFieldNumber = 1;
  inline tetris_protocol::MsgId msgid() const;
  inline void set_msgid(tetris_protocol::MsgId value);
  
  // optional .tetris_protocol.C2SLogin login = 2;
  inline bool has_login() const;
  inline void clear_login();
  static const int kLoginFieldNumber = 2;
  inline const ::tetris_protocol::C2SLogin& login() const;
  inline ::tetris_protocol::C2SLogin* mutable_login();
  inline ::tetris_protocol::C2SLogin* release_login();
  
  // @@protoc_insertion_point(class_scope:tetris_protocol.C2SMsg)
 private:
  inline void set_has_msgid();
  inline void clear_has_msgid();
  inline void set_has_login();
  inline void clear_has_login();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::tetris_protocol::C2SLogin* login_;
  int msgid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_C2S_2eproto();
  friend void protobuf_AssignDesc_C2S_2eproto();
  friend void protobuf_ShutdownFile_C2S_2eproto();
  
  void InitAsDefaultInstance();
  static C2SMsg* default_instance_;
};
// ===================================================================


// ===================================================================

// C2SLogin

// required int32 channelId = 1;
inline bool C2SLogin::has_channelid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void C2SLogin::set_has_channelid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void C2SLogin::clear_has_channelid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void C2SLogin::clear_channelid() {
  channelid_ = 0;
  clear_has_channelid();
}
inline ::google::protobuf::int32 C2SLogin::channelid() const {
  return channelid_;
}
inline void C2SLogin::set_channelid(::google::protobuf::int32 value) {
  set_has_channelid();
  channelid_ = value;
}

// required string channelAccountId = 2;
inline bool C2SLogin::has_channelaccountid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void C2SLogin::set_has_channelaccountid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void C2SLogin::clear_has_channelaccountid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void C2SLogin::clear_channelaccountid() {
  if (channelaccountid_ != &::google::protobuf::internal::kEmptyString) {
    channelaccountid_->clear();
  }
  clear_has_channelaccountid();
}
inline const ::std::string& C2SLogin::channelaccountid() const {
  return *channelaccountid_;
}
inline void C2SLogin::set_channelaccountid(const ::std::string& value) {
  set_has_channelaccountid();
  if (channelaccountid_ == &::google::protobuf::internal::kEmptyString) {
    channelaccountid_ = new ::std::string;
  }
  channelaccountid_->assign(value);
}
inline void C2SLogin::set_channelaccountid(const char* value) {
  set_has_channelaccountid();
  if (channelaccountid_ == &::google::protobuf::internal::kEmptyString) {
    channelaccountid_ = new ::std::string;
  }
  channelaccountid_->assign(value);
}
inline void C2SLogin::set_channelaccountid(const char* value, size_t size) {
  set_has_channelaccountid();
  if (channelaccountid_ == &::google::protobuf::internal::kEmptyString) {
    channelaccountid_ = new ::std::string;
  }
  channelaccountid_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* C2SLogin::mutable_channelaccountid() {
  set_has_channelaccountid();
  if (channelaccountid_ == &::google::protobuf::internal::kEmptyString) {
    channelaccountid_ = new ::std::string;
  }
  return channelaccountid_;
}
inline ::std::string* C2SLogin::release_channelaccountid() {
  clear_has_channelaccountid();
  if (channelaccountid_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = channelaccountid_;
    channelaccountid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional string loginToken = 3;
inline bool C2SLogin::has_logintoken() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void C2SLogin::set_has_logintoken() {
  _has_bits_[0] |= 0x00000004u;
}
inline void C2SLogin::clear_has_logintoken() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void C2SLogin::clear_logintoken() {
  if (logintoken_ != &::google::protobuf::internal::kEmptyString) {
    logintoken_->clear();
  }
  clear_has_logintoken();
}
inline const ::std::string& C2SLogin::logintoken() const {
  return *logintoken_;
}
inline void C2SLogin::set_logintoken(const ::std::string& value) {
  set_has_logintoken();
  if (logintoken_ == &::google::protobuf::internal::kEmptyString) {
    logintoken_ = new ::std::string;
  }
  logintoken_->assign(value);
}
inline void C2SLogin::set_logintoken(const char* value) {
  set_has_logintoken();
  if (logintoken_ == &::google::protobuf::internal::kEmptyString) {
    logintoken_ = new ::std::string;
  }
  logintoken_->assign(value);
}
inline void C2SLogin::set_logintoken(const char* value, size_t size) {
  set_has_logintoken();
  if (logintoken_ == &::google::protobuf::internal::kEmptyString) {
    logintoken_ = new ::std::string;
  }
  logintoken_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* C2SLogin::mutable_logintoken() {
  set_has_logintoken();
  if (logintoken_ == &::google::protobuf::internal::kEmptyString) {
    logintoken_ = new ::std::string;
  }
  return logintoken_;
}
inline ::std::string* C2SLogin::release_logintoken() {
  clear_has_logintoken();
  if (logintoken_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = logintoken_;
    logintoken_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// -------------------------------------------------------------------

// C2SMsg

// required .tetris_protocol.MsgId msgId = 1;
inline bool C2SMsg::has_msgid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void C2SMsg::set_has_msgid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void C2SMsg::clear_has_msgid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void C2SMsg::clear_msgid() {
  msgid_ = 100000;
  clear_has_msgid();
}
inline tetris_protocol::MsgId C2SMsg::msgid() const {
  return static_cast< tetris_protocol::MsgId >(msgid_);
}
inline void C2SMsg::set_msgid(tetris_protocol::MsgId value) {
  GOOGLE_DCHECK(tetris_protocol::MsgId_IsValid(value));
  set_has_msgid();
  msgid_ = value;
}

// optional .tetris_protocol.C2SLogin login = 2;
inline bool C2SMsg::has_login() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void C2SMsg::set_has_login() {
  _has_bits_[0] |= 0x00000002u;
}
inline void C2SMsg::clear_has_login() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void C2SMsg::clear_login() {
  if (login_ != NULL) login_->::tetris_protocol::C2SLogin::Clear();
  clear_has_login();
}
inline const ::tetris_protocol::C2SLogin& C2SMsg::login() const {
  return login_ != NULL ? *login_ : *default_instance_->login_;
}
inline ::tetris_protocol::C2SLogin* C2SMsg::mutable_login() {
  set_has_login();
  if (login_ == NULL) login_ = new ::tetris_protocol::C2SLogin;
  return login_;
}
inline ::tetris_protocol::C2SLogin* C2SMsg::release_login() {
  clear_has_login();
  ::tetris_protocol::C2SLogin* temp = login_;
  login_ = NULL;
  return temp;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace tetris_protocol

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_C2S_2eproto__INCLUDED
