// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "test_pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace hyq {

namespace {

const ::google::protobuf::Descriptor* HyqLogin_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  HyqLogin_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_test_2eproto() {
  protobuf_AddDesc_test_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "test.proto");
  GOOGLE_CHECK(file != NULL);
  HyqLogin_descriptor_ = file->message_type(0);
  static const int HyqLogin_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HyqLogin, channelid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HyqLogin, channelaccountid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HyqLogin, logintoken_),
  };
  HyqLogin_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      HyqLogin_descriptor_,
      HyqLogin::default_instance_,
      HyqLogin_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HyqLogin, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HyqLogin, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(HyqLogin));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_test_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    HyqLogin_descriptor_, &HyqLogin::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_test_2eproto() {
  delete HyqLogin::default_instance_;
  delete HyqLogin_reflection_;
}

void protobuf_AddDesc_test_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\ntest.proto\022\003hyq\"K\n\010HyqLogin\022\021\n\tchannel"
    "Id\030\001 \002(\005\022\030\n\020channelAccountId\030\002 \002(\t\022\022\n\nlo"
    "ginToken\030\003 \001(\t", 94);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "test.proto", &protobuf_RegisterTypes);
  HyqLogin::default_instance_ = new HyqLogin();
  HyqLogin::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_test_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_test_2eproto {
  StaticDescriptorInitializer_test_2eproto() {
    protobuf_AddDesc_test_2eproto();
  }
} static_descriptor_initializer_test_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int HyqLogin::kChannelIdFieldNumber;
const int HyqLogin::kChannelAccountIdFieldNumber;
const int HyqLogin::kLoginTokenFieldNumber;
#endif  // !_MSC_VER

HyqLogin::HyqLogin()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void HyqLogin::InitAsDefaultInstance() {
}

HyqLogin::HyqLogin(const HyqLogin& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void HyqLogin::SharedCtor() {
  _cached_size_ = 0;
  channelid_ = 0;
  channelaccountid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  logintoken_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

HyqLogin::~HyqLogin() {
  SharedDtor();
}

void HyqLogin::SharedDtor() {
  if (channelaccountid_ != &::google::protobuf::internal::kEmptyString) {
    delete channelaccountid_;
  }
  if (logintoken_ != &::google::protobuf::internal::kEmptyString) {
    delete logintoken_;
  }
  if (this != default_instance_) {
  }
}

void HyqLogin::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* HyqLogin::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return HyqLogin_descriptor_;
}

const HyqLogin& HyqLogin::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_test_2eproto();  return *default_instance_;
}

HyqLogin* HyqLogin::default_instance_ = NULL;

HyqLogin* HyqLogin::New() const {
  return new HyqLogin;
}

void HyqLogin::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    channelid_ = 0;
    if (has_channelaccountid()) {
      if (channelaccountid_ != &::google::protobuf::internal::kEmptyString) {
        channelaccountid_->clear();
      }
    }
    if (has_logintoken()) {
      if (logintoken_ != &::google::protobuf::internal::kEmptyString) {
        logintoken_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool HyqLogin::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 channelId = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &channelid_)));
          set_has_channelid();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_channelAccountId;
        break;
      }
      
      // required string channelAccountId = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_channelAccountId:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_channelaccountid()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->channelaccountid().data(), this->channelaccountid().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_loginToken;
        break;
      }
      
      // optional string loginToken = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_loginToken:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_logintoken()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->logintoken().data(), this->logintoken().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void HyqLogin::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 channelId = 1;
  if (has_channelid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->channelid(), output);
  }
  
  // required string channelAccountId = 2;
  if (has_channelaccountid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->channelaccountid().data(), this->channelaccountid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->channelaccountid(), output);
  }
  
  // optional string loginToken = 3;
  if (has_logintoken()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->logintoken().data(), this->logintoken().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->logintoken(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* HyqLogin::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 channelId = 1;
  if (has_channelid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->channelid(), target);
  }
  
  // required string channelAccountId = 2;
  if (has_channelaccountid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->channelaccountid().data(), this->channelaccountid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->channelaccountid(), target);
  }
  
  // optional string loginToken = 3;
  if (has_logintoken()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->logintoken().data(), this->logintoken().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->logintoken(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int HyqLogin::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 channelId = 1;
    if (has_channelid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->channelid());
    }
    
    // required string channelAccountId = 2;
    if (has_channelaccountid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->channelaccountid());
    }
    
    // optional string loginToken = 3;
    if (has_logintoken()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->logintoken());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void HyqLogin::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const HyqLogin* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const HyqLogin*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void HyqLogin::MergeFrom(const HyqLogin& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_channelid()) {
      set_channelid(from.channelid());
    }
    if (from.has_channelaccountid()) {
      set_channelaccountid(from.channelaccountid());
    }
    if (from.has_logintoken()) {
      set_logintoken(from.logintoken());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void HyqLogin::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void HyqLogin::CopyFrom(const HyqLogin& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HyqLogin::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  
  return true;
}

void HyqLogin::Swap(HyqLogin* other) {
  if (other != this) {
    std::swap(channelid_, other->channelid_);
    std::swap(channelaccountid_, other->channelaccountid_);
    std::swap(logintoken_, other->logintoken_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata HyqLogin::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = HyqLogin_descriptor_;
  metadata.reflection = HyqLogin_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace hyq

// @@protoc_insertion_point(global_scope)
