// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: t.proto

#ifndef PROTOBUF_t_2eproto__INCLUDED
#define PROTOBUF_t_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_t_2eproto();
void protobuf_AssignDesc_t_2eproto();
void protobuf_ShutdownFile_t_2eproto();

class C2SLogin;

// ===================================================================

class C2SLogin : public ::google::protobuf::Message {
 public:
  C2SLogin();
  virtual ~C2SLogin();
  
  C2SLogin(const C2SLogin& from);
  
  inline C2SLogin& operator=(const C2SLogin& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const C2SLogin& default_instance();
  
  void Swap(C2SLogin* other);
  
  // implements Message ----------------------------------------------
  
  C2SLogin* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const C2SLogin& from);
  void MergeFrom(const C2SLogin& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 channelId = 1;
  inline bool has_channelid() const;
  inline void clear_channelid();
  static const int kChannelIdFieldNumber = 1;
  inline ::google::protobuf::int32 channelid() const;
  inline void set_channelid(::google::protobuf::int32 value);
  
  // required string channelAccountId = 2;
  inline bool has_channelaccountid() const;
  inline void clear_channelaccountid();
  static const int kChannelAccountIdFieldNumber = 2;
  inline const ::std::string& channelaccountid() const;
  inline void set_channelaccountid(const ::std::string& value);
  inline void set_channelaccountid(const char* value);
  inline void set_channelaccountid(const char* value, size_t size);
  inline ::std::string* mutable_channelaccountid();
  inline ::std::string* release_channelaccountid();
  
  // optional string loginToken = 3;
  inline bool has_logintoken() const;
  inline void clear_logintoken();
  static const int kLoginTokenFieldNumber = 3;
  inline const ::std::string& logintoken() const;
  inline void set_logintoken(const ::std::string& value);
  inline void set_logintoken(const char* value);
  inline void set_logintoken(const char* value, size_t size);
  inline ::std::string* mutable_logintoken();
  inline ::std::string* release_logintoken();
  
  // @@protoc_insertion_point(class_scope:C2SLogin)
 private:
  inline void set_has_channelid();
  inline void clear_has_channelid();
  inline void set_has_channelaccountid();
  inline void clear_has_channelaccountid();
  inline void set_has_logintoken();
  inline void clear_has_logintoken();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* channelaccountid_;
  ::std::string* logintoken_;
  ::google::protobuf::int32 channelid_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_t_2eproto();
  friend void protobuf_AssignDesc_t_2eproto();
  friend void protobuf_ShutdownFile_t_2eproto();
  
  void InitAsDefaultInstance();
  static C2SLogin* default_instance_;
};
// ===================================================================


// ===================================================================

// C2SLogin

// required int32 channelId = 1;
inline bool C2SLogin::has_channelid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void C2SLogin::set_has_channelid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void C2SLogin::clear_has_channelid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void C2SLogin::clear_channelid() {
  channelid_ = 0;
  clear_has_channelid();
}
inline ::google::protobuf::int32 C2SLogin::channelid() const {
  return channelid_;
}
inline void C2SLogin::set_channelid(::google::protobuf::int32 value) {
  set_has_channelid();
  channelid_ = value;
}

// required string channelAccountId = 2;
inline bool C2SLogin::has_channelaccountid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void C2SLogin::set_has_channelaccountid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void C2SLogin::clear_has_channelaccountid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void C2SLogin::clear_channelaccountid() {
  if (channelaccountid_ != &::google::protobuf::internal::kEmptyString) {
    channelaccountid_->clear();
  }
  clear_has_channelaccountid();
}
inline const ::std::string& C2SLogin::channelaccountid() const {
  return *channelaccountid_;
}
inline void C2SLogin::set_channelaccountid(const ::std::string& value) {
  set_has_channelaccountid();
  if (channelaccountid_ == &::google::protobuf::internal::kEmptyString) {
    channelaccountid_ = new ::std::string;
  }
  channelaccountid_->assign(value);
}
inline void C2SLogin::set_channelaccountid(const char* value) {
  set_has_channelaccountid();
  if (channelaccountid_ == &::google::protobuf::internal::kEmptyString) {
    channelaccountid_ = new ::std::string;
  }
  channelaccountid_->assign(value);
}
inline void C2SLogin::set_channelaccountid(const char* value, size_t size) {
  set_has_channelaccountid();
  if (channelaccountid_ == &::google::protobuf::internal::kEmptyString) {
    channelaccountid_ = new ::std::string;
  }
  channelaccountid_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* C2SLogin::mutable_channelaccountid() {
  set_has_channelaccountid();
  if (channelaccountid_ == &::google::protobuf::internal::kEmptyString) {
    channelaccountid_ = new ::std::string;
  }
  return channelaccountid_;
}
inline ::std::string* C2SLogin::release_channelaccountid() {
  clear_has_channelaccountid();
  if (channelaccountid_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = channelaccountid_;
    channelaccountid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional string loginToken = 3;
inline bool C2SLogin::has_logintoken() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void C2SLogin::set_has_logintoken() {
  _has_bits_[0] |= 0x00000004u;
}
inline void C2SLogin::clear_has_logintoken() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void C2SLogin::clear_logintoken() {
  if (logintoken_ != &::google::protobuf::internal::kEmptyString) {
    logintoken_->clear();
  }
  clear_has_logintoken();
}
inline const ::std::string& C2SLogin::logintoken() const {
  return *logintoken_;
}
inline void C2SLogin::set_logintoken(const ::std::string& value) {
  set_has_logintoken();
  if (logintoken_ == &::google::protobuf::internal::kEmptyString) {
    logintoken_ = new ::std::string;
  }
  logintoken_->assign(value);
}
inline void C2SLogin::set_logintoken(const char* value) {
  set_has_logintoken();
  if (logintoken_ == &::google::protobuf::internal::kEmptyString) {
    logintoken_ = new ::std::string;
  }
  logintoken_->assign(value);
}
inline void C2SLogin::set_logintoken(const char* value, size_t size) {
  set_has_logintoken();
  if (logintoken_ == &::google::protobuf::internal::kEmptyString) {
    logintoken_ = new ::std::string;
  }
  logintoken_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* C2SLogin::mutable_logintoken() {
  set_has_logintoken();
  if (logintoken_ == &::google::protobuf::internal::kEmptyString) {
    logintoken_ = new ::std::string;
  }
  return logintoken_;
}
inline ::std::string* C2SLogin::release_logintoken() {
  clear_has_logintoken();
  if (logintoken_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = logintoken_;
    logintoken_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_t_2eproto__INCLUDED
